const translations = {
    vi: {
        title: "Made For Berti Saputri 🎁",
        description: "Hadiah spesial untuk Berti Saputri! Klik untuk melihat kejutan!",
        login: "Masuk dengan Google",
        logout: "Keluar",
        settings: "Pengaturan Website",
        music: "Pengaturan Musik",
        backgroundMusic: "Musik Latar:",
        countdown: "Pengaturan Waktu",
        countdownTime: "Waktu Hitung Mundur:",
        matrix: "Efek Hujan Teks",
        matrixText: "Teks Utama Hujan:",
        matrixColor1: "Warna Hujan 1:",
        matrixColor2: "Warna Hujan 2:",
        sequence: "Pengaturan Pesan Utama",
        sequenceText: "Isi Pesan Utama:",
        sequenceColor: "Warna Teks Utama:",
        gift: "Pengaturan Gambar Animasi",
        giftImage: "Gambar Animasi (opsional):",
        enableBook: "Tampilkan Buku:",
        book: "Pengaturan Halaman Buku",
        enableHeart: "Tampilkan Efek Hati:",
        note: "⏳ Catatan: Website ini berlaku selama 30 hari.",
        follow: "🥰 Follow untuk update website terbaru lainnya!",
        apply: "Terapkan Pengaturan",
        copyright: 'Website dibuat oleh tiktoker: <a href="https://www.tiktok.com/@iamtritoan" target="_blank"> @iamtritoan</a>',
        fullscreen: "Layar Penuh",
        pricingTitle: "Daftar Harga Layanan",
        voucher: "Voucher Diskon:",
        tip: "💸 Tip untuk Penulis:",
        total: "Total:",
        createWebsite: "🎉 Buat Website",
        payAndCreate: "💳 Bayar & Buat Website",
        defaultConfig: "🎉 Gunakan Konfigurasi Default - GRATIS!",
        customMusic: "Musik Latar Kustom",
        extraPage: "Halaman Tambahan",
        heartEffect: "Efek Hati (dalam buku)",
        tipAuthor: "Tip untuk Penulis",
        voucherApplied: "✅ Voucher diterapkan: {code} (-{discount}%)",
        loadingVoucher: "Memuat voucher...",
        noVoucher: "Kamu tidak memiliki voucher!",
        needLoginVoucher: "Silakan login untuk melihat voucher!",
        cannotLoadVoucher: "Gagal memuat voucher!",
        copyLink: "📋 Salin Link",
        viewWebsite: "🔗 Lihat Website",
        close: "✖ Tutup",
        createSuccess: "🎉 Website berhasil dibuat!",
        price: "Harga:",
        shareLink: "Link Berbagi:",
        copySuccess: "Link berhasil disalin!",
        needLogin: "❌ Kamu harus login untuk membuat website!",
        minPay: "❌ Pembayaran minimum adalah 10.000 VNĐ!",
        error: "❌ Terjadi kesalahan!",
        invalidPage: "❌ Struktur halaman tidak valid!",
        uploading: "📤 Mengunggah gambar buku...",
        creating: "🌐 Membuat website...",
        creatingProduct: "📦 Membuat produk...",
        applyingVoucher: "🎫 Menerapkan voucher...",
        applyVoucherSuccess: "✅ Voucher berhasil diterapkan!",
        applyVoucherFail: "⚠️ Gagal menerapkan voucher.",
        cannotCreate: "Gagal membuat website",
        cannotCreateProduct: "Gagal membuat produk",
        cannotApplyVoucher: "Gagal menerapkan voucher!",
        cannotPay: "Gagal memproses pembayaran: ",
        paymentRedirect: "🔄 Mengalihkan ke halaman pembayaran...",
        free: "GRATIS",
        thanks: "Terima kasih banyak! Jangan lupa follow untuk dukungan lebih lanjut.",
        tiktokBtn: "🥰 Lihat TikTok",
        heartQr: "❤️ Buat QR Hati",
        heartQrCopy: "✅ Link QR Hati disalin!",
        copyShare: "📋 Salin link",
        copied: "✅ Tersalin!",
        copyToClipboard: "📋 Link tersalin ke clipboard!",
        copyFail: "❌ Gagal menyalin link!",
        validCoverOnly: "✅ Valid (hanya sampul)",
        validCoverAndPairs: "✅ Valid (sampul + pasangan halaman)",
        invalidMissingPage: "❌ Tidak valid (kurang 1 halaman untuk berpasangan)",
        bookPageInfo: "Info halaman buku:",
        totalPages: "Total halaman",
        status: "Status",
        structure: "Struktur",
        coverOnly: "Hanya Sampul",
        coverAndPairs: "Sampul (1) + {pairs} Pasang Halaman{extra}",
        plusOneExtra: " + 1 Halaman Sisa",
        pageTitleCover: "Halaman {num} (Sampul)",
        pageTitle: "Halaman {num}",
        imageLabel: "Gambar:",
        coverPlaceholder: "Sampul Buku",
        pagePlaceholder: "Halaman {num}",
        noImageAlt: "Belum ada gambar - {placeholder}",
        contentLabel: "Konten:",
        contentPlaceholder: "Masukkan konten untuk halaman {num}",
        addNewPage: "➕ Tambah Halaman Baru",
        emptyPage: "Halaman kosong",
        endOfBook: "Akhir buku",
        loading: "Sedang menyiapkan sesuatu yang spesial...",
        waitingIsHappiness: "Hal baik butuh waktu.",
        invalidPageStructure: "Struktur halaman tidak valid!",
        currentPages: "Sekarang ada {total} halaman.",
        bookStructureGuide: "Struktur buku memerlukan:\n- Halaman 1: Sampul\n- Halaman 2 dst: Berpasangan (2-3, 4-5...)",
        pleaseAddOrRemovePage: "Silakan tambah atau hapus 1 halaman agar struktur valid.",
        fullscreenNotSupported: "Browser kamu tidak mendukung layar penuh!",
        noteSequence: "Catatan: Gunakan tanda | untuk memisahkan baris teks.",
        noteExpire: "⏳ <b>Catatan:</b> Masa aktif website adalah <b>30 hari</b>.",
        followNote: "🥰 Silakan follow untuk update terbaru!",
        on: "Nyala",
        off: "Mati",
        sec3: "3 detik",
        sec5: "5 detik",
        sec10: "10 detik",
        noGif: "Tidak ada",
        notVietnamWarning: 'Jika ada kendala, hubungi admin.',
        isSave: "Simpan QR Selamanya:",
        saveForever: "Selamanya",
        saveForeverPrice: "(Tambah biaya)",
        thirtyDays: "30 Hari",
        expireText: "Kadaluarsa pada",
        colorTheme: "Pilih Warna:",
        settingsHint: "Klik di sini untuk mengatur ulang",
        pinkTheme: "Pink Manis",
        blueTheme: "Biru Keren",
        purpleTheme: "Ungu Cantik",
        customTheme: "Warna Kustom",
        paymentMethod: "Metode Pembayaran",
        bankPayment: "Transfer Bank",
        bankPaymentDesc: "Khusus pengguna lokal",
        paypalPayment: "PayPal",
        paypalPaymentDesc: "Untuk pengguna internasional",
    },
    en: {
        title: "Special Gift for Berti Saputri 🎁",
        description: "A special gift is waiting for you to discover! Press to see the special message!",
        login: "Sign in with Google",
        logout: "Logout",
        settings: "Website Settings",
        music: "Music Settings",
        backgroundMusic: "Background Music:",
        countdown: "Countdown Settings",
        countdownTime: "Countdown Time:",
        matrix: "Matrix Rain Effect Settings",
        matrixText: "Matrix main text:",
        matrixColor1: "Matrix color 1:",
        matrixColor2: "Matrix color 2:",
        sequence: "Main Text Settings",
        sequenceText: "Main text content:",
        sequenceColor: "Main text color:",
        gift: "Animated Image Settings",
        giftImage: "Animated Image (optional):",
        enableBook: "Show book:",
        book: "Book Page Settings",
        enableHeart: "Show heart effect:",
        note: "⏳ Note: The website is valid for 30 days.",
        follow: "🥰 Please follow me to get the latest websites!",
        apply: "Apply Settings",
        copyright: 'Website created by: @iamtritoan',
        fullscreen: "Fullscreen",
        pricingTitle: "Service Pricing",
        voucher: "Discount voucher:",
        tip: "💸 Tip for author:",
        total: "Total:",
        createWebsite: "🎉 Create Website",
        payAndCreate: "💳 Pay & Create Website",
        defaultConfig: "🎉 Using default configuration - FREE!",
        customMusic: "Custom background music",
        extraPage: "Extra page",
        heartEffect: "Heart effect (in book)",
        tipAuthor: "Tip for author",
        voucherApplied: "✅ Voucher applied: {code} (-{discount}%)",
        loadingVoucher: "Loading vouchers...",
        noVoucher: "You have no vouchers!",
        needLoginVoucher: "You need to login to see vouchers!",
        cannotLoadVoucher: "Cannot load vouchers!",
        copyLink: "📋 Copy Link",
        viewWebsite: "🔗 View Website",
        close: "✖ Close",
        createSuccess: "🎉 Website created successfully!",
        price: "Price:",
        shareLink: "Share link:",
        copySuccess: "Link copied!",
        needLogin: "❌ Please login to create website!",
        minPay: "❌ Minimum payment is required!",
        error: "❌ An error occurred!",
        invalidPage: "❌ Invalid page structure!",
        uploading: "📤 Uploading book images...",
        creating: "🌐 Creating website...",
        creatingProduct: "📦 Creating product...",
        applyingVoucher: "🎫 Applying voucher...",
        applyVoucherSuccess: "✅ Voucher applied successfully!",
        applyVoucherFail: "⚠️ Voucher error.",
        cannotCreate: "Cannot create website",
        cannotCreateProduct: "Error creating product",
        cannotApplyVoucher: "Voucher apply failed!",
        cannotPay: "Payment error: ",
        paymentRedirect: "🔄 Redirecting to payment page...",
        free: "FREE",
        thanks: "Thank you so much! Please follow my channel!",
        tiktokBtn: "🥰 View TikTok",
        heartQr: "❤️ Create heart QR",
        heartQrCopy: "✅ Heart QR link copied!",
        copyShare: "📋 Copy link",
        copied: "✅ Copied!",
        copyToClipboard: "📋 Link copied to clipboard!",
        copyFail: "❌ Cannot copy link!",
        validCoverOnly: "✅ Valid (cover only)",
        validCoverAndPairs: "✅ Valid (cover + page pairs)",
        invalidMissingPage: "❌ Invalid (missing 1 page)",
        bookPageInfo: "Book page info:",
        totalPages: "Total pages",
        status: "Status",
        structure: "Structure",
        coverOnly: "Cover only",
        coverAndPairs: "Cover (1) + {pairs} page pairs{extra}",
        plusOneExtra: " + 1 extra page",
        pageTitleCover: "Page {num} (Cover)",
        pageTitle: "Page {num}",
        imageLabel: "Image:",
        coverPlaceholder: "Book Cover",
        pagePlaceholder: "Page {num}",
        noImageAlt: "No image yet - {placeholder}",
        contentLabel: "Content:",
        contentPlaceholder: "Enter content for page {num}",
        addNewPage: "➕ Add New Page",
        emptyPage: "Empty page",
        endOfBook: "End of book",
        loading: "Preparing something special...",
        waitingIsHappiness: "Good things take time.",
        invalidPageStructure: "Invalid page structure!",
        currentPages: "Currently {total} pages.",
        bookStructureGuide: "Book structure required:\n- Page 1: Cover\n- Page pairs (2-3, 4-5...)",
        pleaseAddOrRemovePage: "Please add or remove 1 page.",
        fullscreenNotSupported: "Browser does not support fullscreen!",
        noteSequence: "Note: Use | to separate lines.",
        noteExpire: "⏳ <b>Note:</b> Valid for <b>30 days</b>.",
        followNote: "🥰 Please follow for updates!",
        on: "On",
        off: "Off",
        sec3: "3 seconds",
        sec5: "5 seconds",
        sec10: "10 seconds",
        noGif: "None",
        notVietnamWarning: 'Contact support for issues.',
        isSave: "Save QR forever:",
        saveForever: "forever",
        saveForeverPrice: "(Extra fee)",
        thirtyDays: "30 days",
        expireText: "Expiration is",
        colorTheme: "Choose color:",
        settingsHint: "Click here for settings",
        pinkTheme: "Sweet Pink",
        blueTheme: "Cool Blue",
        purpleTheme: "Dreamy Purple",
        customTheme: "Custom Color",
        paymentMethod: "Payment Method",
        bankPayment: "Bank Transfer",
        bankPaymentDesc: "Local users",
        paypalPayment: "PayPal",
        paypalPaymentDesc: "International users",
    }
};

// Logika fungsi tetap sama
function setLanguage(lang) {
    document.documentElement.lang = lang;
    document.title = translations[lang].title;
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) metaDesc.setAttribute('content', translations[lang].description);

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang][key]) {
            if (translations[lang][key].includes('<b>') || translations[lang][key].includes('<a')) {
                el.innerHTML = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang][key]) {
            el.setAttribute('placeholder', translations[lang][key]);
        }
    });
}

function switchLanguage() {
    const current = localStorage.getItem('lang') || 'vi';
    const next = current === 'vi' ? 'en' : 'vi';
    localStorage.setItem('lang', next);
    setLanguage(next);
}

document.addEventListener('DOMContentLoaded', () => {
    const lang = localStorage.getItem('lang') || 'vi';
    setLanguage(lang);
    const langBtn = document.getElementById('langSwitchBtn');
    if (langBtn) langBtn.onclick = switchLanguage;
});

function t(key, vars = {}) {
    const lang = localStorage.getItem('lang') || 'vi';
    let str = (translations[lang] && translations[lang][key]) || key;
    Object.keys(vars).forEach(k => {
        str = str.replace(`{${k}}`, vars[k]);
    });
    return str;
}